// Code generated by https://github.com/dcaf-mocha/anchor-go. DO NOT EDIT.

package drip

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// DripOrcaWhirlpool is the `dripOrcaWhirlpool` instruction.
type DripOrcaWhirlpool struct {

	// ····· common: [0] = [SIGNER] dripTriggerSource
	//
	// ············· [1] = [WRITE] vault
	//
	// ············· [2] = [] vaultProtoConfig
	//
	// ············· [3] = [] lastVaultPeriod
	//
	// ············· [4] = [WRITE] currentVaultPeriod
	//
	// ············· [5] = [WRITE] vaultTokenAAccount
	//
	// ············· [6] = [WRITE] vaultTokenBAccount
	//
	// ············· [7] = [WRITE] swapTokenAAccount
	//
	// ············· [8] = [WRITE] swapTokenBAccount
	//
	// ············· [9] = [WRITE] dripFeeTokenAAccount
	//
	// ············· [10] = [] tokenProgram
	//
	// [11] = [WRITE] whirlpool
	//
	// [12] = [WRITE] tickArray0
	//
	// [13] = [WRITE] tickArray1
	//
	// [14] = [WRITE] tickArray2
	//
	// [15] = [] oracle
	//
	// [16] = [] whirlpoolProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

type DripOrcaWhirlpoolAccounts struct {
	Common struct {
		DripTriggerSource    ag_solanago.PublicKey
		Vault                ag_solanago.PublicKey
		VaultProtoConfig     ag_solanago.PublicKey
		LastVaultPeriod      ag_solanago.PublicKey
		CurrentVaultPeriod   ag_solanago.PublicKey
		VaultTokenAAccount   ag_solanago.PublicKey
		VaultTokenBAccount   ag_solanago.PublicKey
		SwapTokenAAccount    ag_solanago.PublicKey
		SwapTokenBAccount    ag_solanago.PublicKey
		DripFeeTokenAAccount ag_solanago.PublicKey
		TokenProgram         ag_solanago.PublicKey
	}
	Whirlpool        ag_solanago.PublicKey
	TickArray0       ag_solanago.PublicKey
	TickArray1       ag_solanago.PublicKey
	TickArray2       ag_solanago.PublicKey
	Oracle           ag_solanago.PublicKey
	WhirlpoolProgram ag_solanago.PublicKey
}

// NewDripOrcaWhirlpoolInstructionBuilder creates a new `DripOrcaWhirlpool` instruction builder.
func NewDripOrcaWhirlpoolInstructionBuilder() *DripOrcaWhirlpool {
	nd := &DripOrcaWhirlpool{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 17),
	}
	return nd
}

func (inst *DripOrcaWhirlpool) GetDripOrcaWhirlpoolAccounts() *DripOrcaWhirlpoolAccounts {
	res := &DripOrcaWhirlpoolAccounts{}
	res.Common.DripTriggerSource = inst.AccountMetaSlice[0].PublicKey
	res.Common.Vault = inst.AccountMetaSlice[1].PublicKey
	res.Common.VaultProtoConfig = inst.AccountMetaSlice[2].PublicKey
	res.Common.LastVaultPeriod = inst.AccountMetaSlice[3].PublicKey
	res.Common.CurrentVaultPeriod = inst.AccountMetaSlice[4].PublicKey
	res.Common.VaultTokenAAccount = inst.AccountMetaSlice[5].PublicKey
	res.Common.VaultTokenBAccount = inst.AccountMetaSlice[6].PublicKey
	res.Common.SwapTokenAAccount = inst.AccountMetaSlice[7].PublicKey
	res.Common.SwapTokenBAccount = inst.AccountMetaSlice[8].PublicKey
	res.Common.DripFeeTokenAAccount = inst.AccountMetaSlice[9].PublicKey
	res.Common.TokenProgram = inst.AccountMetaSlice[10].PublicKey
	res.Whirlpool = inst.AccountMetaSlice[11].PublicKey
	res.TickArray0 = inst.AccountMetaSlice[12].PublicKey
	res.TickArray1 = inst.AccountMetaSlice[13].PublicKey
	res.TickArray2 = inst.AccountMetaSlice[14].PublicKey
	res.Oracle = inst.AccountMetaSlice[15].PublicKey
	res.WhirlpoolProgram = inst.AccountMetaSlice[16].PublicKey
	return res
}

type DripOrcaWhirlpoolCommonAccountsBuilder struct {
	ag_solanago.AccountMetaSlice `bin:"-"`
}

func NewDripOrcaWhirlpoolCommonAccountsBuilder() *DripOrcaWhirlpoolCommonAccountsBuilder {
	return &DripOrcaWhirlpoolCommonAccountsBuilder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
}

func (inst *DripOrcaWhirlpool) SetCommonAccountsFromBuilder(dripOrcaWhirlpoolCommonAccountsBuilder *DripOrcaWhirlpoolCommonAccountsBuilder) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[0] = dripOrcaWhirlpoolCommonAccountsBuilder.GetDripTriggerSourceAccount()
	inst.AccountMetaSlice[1] = dripOrcaWhirlpoolCommonAccountsBuilder.GetVaultAccount()
	inst.AccountMetaSlice[2] = dripOrcaWhirlpoolCommonAccountsBuilder.GetVaultProtoConfigAccount()
	inst.AccountMetaSlice[3] = dripOrcaWhirlpoolCommonAccountsBuilder.GetLastVaultPeriodAccount()
	inst.AccountMetaSlice[4] = dripOrcaWhirlpoolCommonAccountsBuilder.GetCurrentVaultPeriodAccount()
	inst.AccountMetaSlice[5] = dripOrcaWhirlpoolCommonAccountsBuilder.GetVaultTokenAAccountAccount()
	inst.AccountMetaSlice[6] = dripOrcaWhirlpoolCommonAccountsBuilder.GetVaultTokenBAccountAccount()
	inst.AccountMetaSlice[7] = dripOrcaWhirlpoolCommonAccountsBuilder.GetSwapTokenAAccountAccount()
	inst.AccountMetaSlice[8] = dripOrcaWhirlpoolCommonAccountsBuilder.GetSwapTokenBAccountAccount()
	inst.AccountMetaSlice[9] = dripOrcaWhirlpoolCommonAccountsBuilder.GetDripFeeTokenAAccountAccount()
	inst.AccountMetaSlice[10] = dripOrcaWhirlpoolCommonAccountsBuilder.GetTokenProgramAccount()
	return inst
}

// SetDripTriggerSourceAccount sets the "dripTriggerSource" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetDripTriggerSourceAccount(dripTriggerSource ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(dripTriggerSource).SIGNER()
	return inst
}

// GetDripTriggerSourceAccount gets the "dripTriggerSource" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetDripTriggerSourceAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetVaultAccount sets the "vault" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetVaultAccount(vault ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(vault).WRITE()
	return inst
}

// GetVaultAccount gets the "vault" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetVaultProtoConfigAccount sets the "vaultProtoConfig" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetVaultProtoConfigAccount(vaultProtoConfig ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(vaultProtoConfig)
	return inst
}

// GetVaultProtoConfigAccount gets the "vaultProtoConfig" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetVaultProtoConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetLastVaultPeriodAccount sets the "lastVaultPeriod" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetLastVaultPeriodAccount(lastVaultPeriod ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(lastVaultPeriod)
	return inst
}

// GetLastVaultPeriodAccount gets the "lastVaultPeriod" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetLastVaultPeriodAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetCurrentVaultPeriodAccount sets the "currentVaultPeriod" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetCurrentVaultPeriodAccount(currentVaultPeriod ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(currentVaultPeriod).WRITE()
	return inst
}

// GetCurrentVaultPeriodAccount gets the "currentVaultPeriod" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetCurrentVaultPeriodAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetVaultTokenAAccountAccount sets the "vaultTokenAAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetVaultTokenAAccountAccount(vaultTokenAAccount ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(vaultTokenAAccount).WRITE()
	return inst
}

// GetVaultTokenAAccountAccount gets the "vaultTokenAAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetVaultTokenAAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetVaultTokenBAccountAccount sets the "vaultTokenBAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetVaultTokenBAccountAccount(vaultTokenBAccount ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(vaultTokenBAccount).WRITE()
	return inst
}

// GetVaultTokenBAccountAccount gets the "vaultTokenBAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetVaultTokenBAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSwapTokenAAccountAccount sets the "swapTokenAAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetSwapTokenAAccountAccount(swapTokenAAccount ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(swapTokenAAccount).WRITE()
	return inst
}

// GetSwapTokenAAccountAccount gets the "swapTokenAAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetSwapTokenAAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetSwapTokenBAccountAccount sets the "swapTokenBAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetSwapTokenBAccountAccount(swapTokenBAccount ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(swapTokenBAccount).WRITE()
	return inst
}

// GetSwapTokenBAccountAccount gets the "swapTokenBAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetSwapTokenBAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetDripFeeTokenAAccountAccount sets the "dripFeeTokenAAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetDripFeeTokenAAccountAccount(dripFeeTokenAAccount ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(dripFeeTokenAAccount).WRITE()
	return inst
}

// GetDripFeeTokenAAccountAccount gets the "dripFeeTokenAAccount" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetDripFeeTokenAAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *DripOrcaWhirlpoolCommonAccountsBuilder {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *DripOrcaWhirlpoolCommonAccountsBuilder) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetWhirlpoolAccount sets the "whirlpool" account.
func (inst *DripOrcaWhirlpool) SetWhirlpoolAccount(whirlpool ag_solanago.PublicKey) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(whirlpool).WRITE()
	return inst
}

// GetWhirlpoolAccount gets the "whirlpool" account.
func (inst *DripOrcaWhirlpool) GetWhirlpoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetTickArray0Account sets the "tickArray0" account.
func (inst *DripOrcaWhirlpool) SetTickArray0Account(tickArray0 ag_solanago.PublicKey) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(tickArray0).WRITE()
	return inst
}

// GetTickArray0Account gets the "tickArray0" account.
func (inst *DripOrcaWhirlpool) GetTickArray0Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetTickArray1Account sets the "tickArray1" account.
func (inst *DripOrcaWhirlpool) SetTickArray1Account(tickArray1 ag_solanago.PublicKey) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(tickArray1).WRITE()
	return inst
}

// GetTickArray1Account gets the "tickArray1" account.
func (inst *DripOrcaWhirlpool) GetTickArray1Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetTickArray2Account sets the "tickArray2" account.
func (inst *DripOrcaWhirlpool) SetTickArray2Account(tickArray2 ag_solanago.PublicKey) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(tickArray2).WRITE()
	return inst
}

// GetTickArray2Account gets the "tickArray2" account.
func (inst *DripOrcaWhirlpool) GetTickArray2Account() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetOracleAccount sets the "oracle" account.
func (inst *DripOrcaWhirlpool) SetOracleAccount(oracle ag_solanago.PublicKey) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(oracle)
	return inst
}

// GetOracleAccount gets the "oracle" account.
func (inst *DripOrcaWhirlpool) GetOracleAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

// SetWhirlpoolProgramAccount sets the "whirlpoolProgram" account.
func (inst *DripOrcaWhirlpool) SetWhirlpoolProgramAccount(whirlpoolProgram ag_solanago.PublicKey) *DripOrcaWhirlpool {
	inst.AccountMetaSlice[16] = ag_solanago.Meta(whirlpoolProgram)
	return inst
}

// GetWhirlpoolProgramAccount gets the "whirlpoolProgram" account.
func (inst *DripOrcaWhirlpool) GetWhirlpoolProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(16)
}

func (inst DripOrcaWhirlpool) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_DripOrcaWhirlpool,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst DripOrcaWhirlpool) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *DripOrcaWhirlpool) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CommonDripTriggerSource is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CommonVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CommonVaultProtoConfig is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.CommonLastVaultPeriod is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.CommonCurrentVaultPeriod is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.CommonVaultTokenAAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.CommonVaultTokenBAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.CommonSwapTokenAAccount is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.CommonSwapTokenBAccount is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.CommonDripFeeTokenAAccount is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.CommonTokenProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Whirlpool is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.TickArray0 is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.TickArray1 is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.TickArray2 is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.Oracle is not set")
		}
		if inst.AccountMetaSlice[16] == nil {
			return errors.New("accounts.WhirlpoolProgram is not set")
		}
	}
	return nil
}

func (inst *DripOrcaWhirlpool) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("DripOrcaWhirlpool")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=17]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" common/dripTriggerSource", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("             common/vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  common/vaultProtoConfig", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   common/lastVaultPeriod", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("common/currentVaultPeriod", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       common/vaultTokenA", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("       common/vaultTokenB", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        common/swapTokenA", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("        common/swapTokenB", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("     common/dripFeeTokenA", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("      common/tokenProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("                whirlpool", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("               tickArray0", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("               tickArray1", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("               tickArray2", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta("                   oracle", inst.AccountMetaSlice.Get(15)))
						accountsBranch.Child(ag_format.Meta("         whirlpoolProgram", inst.AccountMetaSlice.Get(16)))
					})
				})
		})
}

func (obj DripOrcaWhirlpool) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *DripOrcaWhirlpool) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewDripOrcaWhirlpoolInstruction declares a new DripOrcaWhirlpool instruction with the provided parameters and accounts.
func NewDripOrcaWhirlpoolInstruction(
	// Accounts:
	commonDripTriggerSource ag_solanago.PublicKey,
	commonVault ag_solanago.PublicKey,
	commonVaultProtoConfig ag_solanago.PublicKey,
	commonLastVaultPeriod ag_solanago.PublicKey,
	commonCurrentVaultPeriod ag_solanago.PublicKey,
	commonVaultTokenAAccount ag_solanago.PublicKey,
	commonVaultTokenBAccount ag_solanago.PublicKey,
	commonSwapTokenAAccount ag_solanago.PublicKey,
	commonSwapTokenBAccount ag_solanago.PublicKey,
	commonDripFeeTokenAAccount ag_solanago.PublicKey,
	commonTokenProgram ag_solanago.PublicKey,
	whirlpool ag_solanago.PublicKey,
	tickArray0 ag_solanago.PublicKey,
	tickArray1 ag_solanago.PublicKey,
	tickArray2 ag_solanago.PublicKey,
	oracle ag_solanago.PublicKey,
	whirlpoolProgram ag_solanago.PublicKey) *DripOrcaWhirlpool {
	return NewDripOrcaWhirlpoolInstructionBuilder().
		SetCommonAccountsFromBuilder(
			NewDripOrcaWhirlpoolCommonAccountsBuilder().
				SetDripTriggerSourceAccount(commonDripTriggerSource).
				SetVaultAccount(commonVault).
				SetVaultProtoConfigAccount(commonVaultProtoConfig).
				SetLastVaultPeriodAccount(commonLastVaultPeriod).
				SetCurrentVaultPeriodAccount(commonCurrentVaultPeriod).
				SetVaultTokenAAccountAccount(commonVaultTokenAAccount).
				SetVaultTokenBAccountAccount(commonVaultTokenBAccount).
				SetSwapTokenAAccountAccount(commonSwapTokenAAccount).
				SetSwapTokenBAccountAccount(commonSwapTokenBAccount).
				SetDripFeeTokenAAccountAccount(commonDripFeeTokenAAccount).
				SetTokenProgramAccount(commonTokenProgram),
		).
		SetWhirlpoolAccount(whirlpool).
		SetTickArray0Account(tickArray0).
		SetTickArray1Account(tickArray1).
		SetTickArray2Account(tickArray2).
		SetOracleAccount(oracle).
		SetWhirlpoolProgramAccount(whirlpoolProgram)
}
