// Code generated by https://github.com/dcaf-mocha/anchor-go. DO NOT EDIT.

package drip

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitVaultPeriod is the `initVaultPeriod` instruction.
type InitVaultPeriod struct {
	Params *InitializeVaultPeriodParams

	// [0] = [WRITE] vaultPeriod
	//
	// [1] = [] vault
	//
	// [2] = [WRITE, SIGNER] creator
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

type InitVaultPeriodAccounts struct {
	VaultPeriod   ag_solanago.PublicKey
	Vault         ag_solanago.PublicKey
	Creator       ag_solanago.PublicKey
	SystemProgram ag_solanago.PublicKey
}

// NewInitVaultPeriodInstructionBuilder creates a new `InitVaultPeriod` instruction builder.
func NewInitVaultPeriodInstructionBuilder() *InitVaultPeriod {
	nd := &InitVaultPeriod{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

func (inst *InitVaultPeriod) GetInitVaultPeriodAccounts() *InitVaultPeriodAccounts {
	res := &InitVaultPeriodAccounts{}
	if inst.AccountMetaSlice[0] != nil {
		res.VaultPeriod = inst.AccountMetaSlice[0].PublicKey
	}
	if inst.AccountMetaSlice[1] != nil {
		res.Vault = inst.AccountMetaSlice[1].PublicKey
	}
	if inst.AccountMetaSlice[2] != nil {
		res.Creator = inst.AccountMetaSlice[2].PublicKey
	}
	if inst.AccountMetaSlice[3] != nil {
		res.SystemProgram = inst.AccountMetaSlice[3].PublicKey
	}
	return res
}

// SetParams sets the "params" parameter.
func (inst *InitVaultPeriod) SetParams(params InitializeVaultPeriodParams) *InitVaultPeriod {
	inst.Params = &params
	return inst
}

// SetVaultPeriodAccount sets the "vaultPeriod" account.
func (inst *InitVaultPeriod) SetVaultPeriodAccount(vaultPeriod ag_solanago.PublicKey) *InitVaultPeriod {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(vaultPeriod).WRITE()
	return inst
}

// GetVaultPeriodAccount gets the "vaultPeriod" account.
func (inst *InitVaultPeriod) GetVaultPeriodAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetVaultAccount sets the "vault" account.
func (inst *InitVaultPeriod) SetVaultAccount(vault ag_solanago.PublicKey) *InitVaultPeriod {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(vault)
	return inst
}

// GetVaultAccount gets the "vault" account.
func (inst *InitVaultPeriod) GetVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCreatorAccount sets the "creator" account.
func (inst *InitVaultPeriod) SetCreatorAccount(creator ag_solanago.PublicKey) *InitVaultPeriod {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(creator).WRITE().SIGNER()
	return inst
}

// GetCreatorAccount gets the "creator" account.
func (inst *InitVaultPeriod) GetCreatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitVaultPeriod) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitVaultPeriod {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitVaultPeriod) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst InitVaultPeriod) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitVaultPeriod,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitVaultPeriod) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitVaultPeriod) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.VaultPeriod is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Vault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Creator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *InitVaultPeriod) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitVaultPeriod")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  vaultPeriod", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      creator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj InitVaultPeriod) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *InitVaultPeriod) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewInitVaultPeriodInstruction declares a new InitVaultPeriod instruction with the provided parameters and accounts.
func NewInitVaultPeriodInstruction(
	// Parameters:
	params InitializeVaultPeriodParams,
	// Accounts:
	vaultPeriod ag_solanago.PublicKey,
	vault ag_solanago.PublicKey,
	creator ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *InitVaultPeriod {
	return NewInitVaultPeriodInstructionBuilder().
		SetParams(params).
		SetVaultPeriodAccount(vaultPeriod).
		SetVaultAccount(vault).
		SetCreatorAccount(creator).
		SetSystemProgramAccount(systemProgram)
}
